"""add tables

Revision ID: 7e408a54eeb8
Revises: 9a0bb96df9e3
Create Date: 2020-08-06 16:04:28.515667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e408a54eeb8'
down_revision = '9a0bb96df9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
