"""add tables

Revision ID: 9a0bb96df9e3
Revises: 9e0b3bb900b1
Create Date: 2020-08-06 15:59:38.071658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0bb96df9e3'
down_revision = '9e0b3bb900b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
